language: ruby
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.2
bundler_args: --without production

env:
  - KITTYPASS_MAIL='please-change-me-at-config-initializers-devise@example.com'

before_script:
  - cp config/database.yml.example config/database.yml

addons:
  code_climate:
    repo_token: a6036ed6b584d96f883c1ee0fc2b646b5aece52b1700c7bc6e7ebab5f2752fea
