language: ruby
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.1
bundler_args: --without production

env:
  - KITTYPASS_MAIL='please-change-me-at-config-initializers-devise@example.com'

before_script:
  - cp config/database.yml.example config/database.yml

addons:
  code_climate:
    repo_token: b2f10f0e0563351f33a081d9d2e2033c65ef594b7fe44d206c4bbd56ce9a810d
